<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fincon.Application\Fincon.Application.csproj" />
    <ProjectReference Include="..\Fincon.Domain\Fincon.Domain.csproj" />
  </ItemGroup>

</Project>
